server:
  port: 8080

spring:
  application:
    name: xiaohuangshu-auth
  profiles:
    active: dev
  config:
    import: optional:nacos:xiaohuangshu-auth.yaml
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
        file-extension: yaml
        refresh-enabled: true
        prefix: ${spring.application.name}
        namespace: xiaohuangshu
      discovery:
        enabled: true #启用服务发现
        group: DEFAULT_GROUP
        namespace: xiaohuangshu
        server-addr: 127.0.0.1:8848

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

sa-token:
  token-name: Authorization #token名称 也是cookie名称
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: random-128
  is-log: true
  token-prefix: Bearer #token前缀

alarm:
  type: sms

rate-limit:
  api:
    limit: 100
